#! /usr/bin/env ruby
require 'rubygems'
require 'trollop'
require 'line_ender'

include LineEnder

opts = Trollop::options do
  banner <<-EOS
Synopsis: le is a line ender script to be used from the command prompt if you put it in your path
Usage: le [flags] [-o outfile] inputfile
Note: don't have to set --no-unix flag if looking for different endings ... will override.
Flags:
EOS
  opt :windows, "Windows ending", :default => false
  opt :unix, "Unix ending", :default => true
  opt :mac, "Mac ending", :default => false
  opt :debug, "Debug mode", :default => false
  opt :output, "Output to another file", :type => :string
end

p opts if opts[:debug]

outfile = opts[:output]
ending = nil
ending = opts[:windows] ? LineEnder::Ending::Windows : ending
ending = opts[:mac] ? LineEnder::Ending::Mac : ending 
ending = opts[:unix] ? LineEnder::Ending::Unix : ending if ending.nil?

if ARGV.length != 1
  puts "Missing or too many INPUTFILE argument(s)."
  puts "example: le -m -o fixed.txt somefile.txt"
  puts "Try the -h flag for help on flags"
  exit 0
end

infile = ARGV[0]

if opts[:debug]
  puts "outfile: #{outfile}, #{outfile.inspect}"
  puts "infile: #{infile}, #{infile.inspect}" 
  puts "ending: #{ending.inspect}"
end

ending_string = ""
case ending
when LineEnder::Ending::Windows
  ending_string = "windows"
when LineEnder::Ending::Unix
  ending_string = "unix"
when LineEnder::Ending::Mac
  ending_string = "mac"
else
  ending_string = "unix"
end

if outfile
  output_to_file( infile, ending, outfile )
  puts "Succesfully created #{outfile}, with #{ending_string}-style line endings!"
else
  output_to_file( infile, ending )
  puts "Successfully updated #{infile}, with #{ending_string}-style line endings!"
end

